# Use a imagem oficial do Node.js com a versão 18
FROM node:18

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /src

# Copie o arquivo package.json e package-lock.json
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie os arquivos do aplicativo para o contêiner
COPY . .

# Exponha a porta que o aplicativo estará ouvindo
EXPOSE 8080

# Comando para iniciar o ambiente de desenvolvimento
CMD ["npm", "run", "dev"]
